spring:
   datasource:
      url: jdbc:mysql://localhost:3306/oktasync_uat
      username: oktasync
      password: oktasync0001
      driverClassName: com.mysql.cj.jdbc.Driver
      hikari:
            maximum-pool-size: 20
            connectionTimeout: 30000
            idleTimeout: 600000
            maxLifetime: 600000
            minimumIdle: 5
            pool-name: app-pool
            auto-commit: true
   jpa:
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
         ddl-auto: update
         
ugdn:
   api:
      url: https://appuat.uplonline.com/ugdn.sync.api/api/